# Test your FastAPI endpoints

# Test the home page
GET http://127.0.0.1:8000/
Accept: text/html

###
# Test a reachable pdf file
GET http://127.0.0.1:8000/https://coursepals-pdfs.s3.us-west-1.amazonaws.com/pdf3.pdf
Accept: text/json

###

GET http://127.0.0.1:8000/https://github.com/AshleyXM/pdf-reader
Accept: text/json

###

GET http://127.0.0.1:8000/https://coursepals-pdfs.s3.us-west-1.amazonaws.com/pdf.pdf
Accept: text/json

###